package views;

import java.awt.TextField;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import libreria.Objeto;
import viewModels.ConfiguratioViewModel;

/**
 *
 * @author ioriyagamy
 */
public class Moneda extends javax.swing.JPanel {

    private final List<JRadioButton> radio;
    ConfiguratioViewModel config;

    /**
     * Creates new form Moneda
     */
    public Moneda() {
        initComponents();
        radio = new ArrayList<>();
        radio.add(rbPeso);
        radio.add(rbDolar);
        radio.add(RadioButtonConfigIntereses);
        ArrayList<JTextField> textField = new ArrayList<>();
        textField.add(txtFielconfigIntereses);
        ArrayList<JLabel> label = new ArrayList<>();
        label.add(lbConfigMessageIntereses);
        label.add(lbConfigIntereses);
        config = new ConfiguratioViewModel(radio, textField, label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelSuperior = new javax.swing.JPanel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        panelHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rbDolar = new javax.swing.JRadioButton();
        rbPeso = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtFielconfigIntereses = new javax.swing.JTextField();
        lbConfigMessageIntereses = new javax.swing.JLabel();
        RadioButtonConfigIntereses = new javax.swing.JRadioButton();
        lbConfigIntereses = new javax.swing.JLabel();
        btConfigAddIntereses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        panelSuperior.setBackground(new java.awt.Color(0, 66, 123));
        panelSuperior.setPreferredSize(new java.awt.Dimension(1017, 30));

        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cerrar.png"))); // NOI18N
        rSButtonMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMetro1MouseClicked(evt);
            }
        });
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addGap(0, 1287, Short.MAX_VALUE)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonMetro1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(panelSuperior);
        panelSuperior.setBounds(0, 0, 1320, 30);

        panelHead.setBackground(new java.awt.Color(255, 255, 255));
        panelHead.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Manjari Thin", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Configuraciones");

        javax.swing.GroupLayout panelHeadLayout = new javax.swing.GroupLayout(panelHead);
        panelHead.setLayout(panelHeadLayout);
        panelHeadLayout.setHorizontalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 1143, Short.MAX_VALUE))
        );
        panelHeadLayout.setVerticalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panelHead);
        panelHead.setBounds(0, 30, 1320, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO / MONEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Manjari Thin", 1, 14))); // NOI18N

        rbDolar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbDolar);
        rbDolar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbDolar.setText("Dolar Estadounidense");
        rbDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDolarActionPerformed(evt);
            }
        });

        rbPeso.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPeso);
        rbPeso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbPeso.setText("Peso Dominicano");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDolar)
                    .addComponent(rbPeso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(rbPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDolar)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Manjari Thin", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Tipo de Moneda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel2)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tipo Moneda", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO / INTERESES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Manjari Thin", 1, 14))); // NOI18N

        txtFielconfigIntereses.setBackground(new java.awt.Color(255, 255, 255));
        txtFielconfigIntereses.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFielconfigIntereses.setForeground(new java.awt.Color(0, 0, 0));
        txtFielconfigIntereses.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtFielconfigIntereses.setOpaque(false);
        txtFielconfigIntereses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFielconfigInteresesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFielconfigInteresesKeyTyped(evt);
            }
        });

        lbConfigMessageIntereses.setText("Mensaje");

        RadioButtonConfigIntereses.setText("Intereses");
        RadioButtonConfigIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonConfigInteresesActionPerformed(evt);
            }
        });

        lbConfigIntereses.setText("Intereses");

        btConfigAddIntereses.setText("Registrar");
        btConfigAddIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfigAddInteresesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbConfigIntereses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioButtonConfigIntereses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbConfigMessageIntereses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(txtFielconfigIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btConfigAddIntereses))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFielconfigIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConfigAddIntereses))
                .addGap(18, 18, 18)
                .addComponent(lbConfigMessageIntereses)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonConfigIntereses)
                .addGap(29, 29, 29)
                .addComponent(lbConfigIntereses)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Manjari Thin", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Registro de Intereses");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(248, 248, 248))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registro de Interese", jPanel3);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 100, 750, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro1MouseClicked
        this.hide();
    }//GEN-LAST:event_rSButtonMetro1MouseClicked

    private void rbDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDolarActionPerformed

    private void txtFielconfigInteresesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFielconfigInteresesKeyTyped
        Objeto.events.numberDecimalKeyPress(evt, txtFielconfigIntereses);
    }//GEN-LAST:event_txtFielconfigInteresesKeyTyped

    private void btConfigAddInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfigAddInteresesActionPerformed
        config.RegistrarIntereses();
    }//GEN-LAST:event_btConfigAddInteresesActionPerformed
 
    private void txtFielconfigInteresesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFielconfigInteresesKeyReleased
        lbConfigMessageIntereses.setText("");
    }//GEN-LAST:event_txtFielconfigInteresesKeyReleased

    private void RadioButtonConfigInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonConfigInteresesActionPerformed
        lbConfigMessageIntereses.setText("");
    }//GEN-LAST:event_RadioButtonConfigInteresesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonConfigIntereses;
    private javax.swing.JButton btConfigAddIntereses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbConfigIntereses;
    private javax.swing.JLabel lbConfigMessageIntereses;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelSuperior;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private javax.swing.JRadioButton rbDolar;
    private javax.swing.JRadioButton rbPeso;
    private javax.swing.JTextField txtFielconfigIntereses;
    // End of variables declaration//GEN-END:variables
}
