package views;

import viewModels.ClientViewModel;

/**
 *
 * @author ioriyagamy
 */
public class OtraPlantilla extends javax.swing.JPanel {

//    private final ClientViewModel clientViewModel;

    public OtraPlantilla() {
        initComponents();
        Object[] objects = {
            TBReportDeuda
        };
//        clientViewModel = new ClientViewModel();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbReportName4 = new javax.swing.JLabel();
        lbReportName5 = new javax.swing.JLabel();
        lbReportName6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        lbReportName7 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBReportDeuda = TBReportDeuda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        btClientPage1 = new rsbuttom.RSButtonMetro();
        btClientPage2 = new rsbuttom.RSButtonMetro();
        btClientPage3 = new rsbuttom.RSButtonMetro();
        btClientPage4 = new rsbuttom.RSButtonMetro();
        lbClientPage = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setPreferredSize(new java.awt.Dimension(785, 30));

        rSButtonMetro1.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cerrar.png"))); // NOI18N
        rSButtonMetro1.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonMetro1.setColorNormal(new java.awt.Color(102, 102, 102));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1513, Short.MAX_VALUE)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonMetro1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AJUSTE / FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Manjari Thin", 2, 16), new java.awt.Color(102, 102, 102))); // NOI18N

        lbReportName4.setText("Fecha Deuda");

        lbReportName5.setText("Dias ");

        lbReportName6.setText("Dias Restantes");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        lbReportName7.setText("Extender Dias");

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(597, 180));
    dateChooserCombo1.setFormat(0);
    dateChooserCombo1.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(lbReportName5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1)
                    .addGap(107, 107, 107))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(lbReportName6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                    .addComponent(lbReportName7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbReportName4)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(lbReportName4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lbReportName6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lbReportName5)
                    .addGap(6, 6, 6))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbReportName7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox1)))
            .addGap(35, 35, 35))
    );

    jLabel5.setFont(new java.awt.Font("Manjari Thin", 0, 24)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 102, 204));
    jLabel5.setText("Reportes de Pago");

    jPanel4.setBackground(new java.awt.Color(204, 204, 204));
    jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    TBReportDeuda.setBackground(new java.awt.Color(255, 255, 255));
    TBReportDeuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    TBReportDeuda.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {},
            {},
            {},
            {}
        },
        new String [] {

        }
    ));
    TBReportDeuda.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            TBReportDeudaMouseClicked(evt);
        }
    });
    TBReportDeuda.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            TBReportDeudaKeyReleased(evt);
        }
    });
    jScrollPane2.setViewportView(TBReportDeuda);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addContainerGap())
    );

    btClientPage1.setBackground(new java.awt.Color(255, 255, 255));
    btClientPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/left-arrow(1).png"))); // NOI18N
    btClientPage1.setColorBorde(null);
    btClientPage1.setColorHover(new java.awt.Color(102, 102, 102));
    btClientPage1.setColorNormal(new java.awt.Color(255, 255, 255));
    btClientPage1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btClientPage1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btClientPage1ActionPerformed(evt);
        }
    });

    btClientPage2.setBackground(new java.awt.Color(255, 255, 255));
    btClientPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/left-arrow.png"))); // NOI18N
    btClientPage2.setColorBorde(null);
    btClientPage2.setColorHover(new java.awt.Color(102, 102, 102));
    btClientPage2.setColorNormal(new java.awt.Color(255, 255, 255));
    btClientPage2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btClientPage2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btClientPage2ActionPerformed(evt);
        }
    });

    btClientPage3.setBackground(new java.awt.Color(255, 255, 255));
    btClientPage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next.png"))); // NOI18N
    btClientPage3.setColorBorde(null);
    btClientPage3.setColorHover(new java.awt.Color(102, 102, 102));
    btClientPage3.setColorNormal(new java.awt.Color(255, 255, 255));
    btClientPage3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btClientPage3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btClientPage3ActionPerformed(evt);
        }
    });

    btClientPage4.setBackground(new java.awt.Color(255, 255, 255));
    btClientPage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/right-arrow.png"))); // NOI18N
    btClientPage4.setColorBorde(null);
    btClientPage4.setColorHover(new java.awt.Color(102, 102, 102));
    btClientPage4.setColorNormal(new java.awt.Color(255, 255, 255));
    btClientPage4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btClientPage4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btClientPage4ActionPerformed(evt);
        }
    });

    lbClientPage.setText("Paginas");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(559, 559, 559)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(363, 363, 363)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbClientPage)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btClientPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btClientPage2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btClientPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btClientPage4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(286, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(70, 70, 70)
            .addComponent(jLabel5)
            .addGap(26, 26, 26)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbClientPage)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btClientPage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btClientPage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btClientPage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btClientPage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(462, Short.MAX_VALUE))
    );

    add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        this.hide();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btClientPage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientPage4ActionPerformed
//        clientViewModel.pager("Last");
    }//GEN-LAST:event_btClientPage4ActionPerformed

    private void btClientPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientPage3ActionPerformed
//        clientViewModel.pager("Next");
    }//GEN-LAST:event_btClientPage3ActionPerformed

    private void btClientPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientPage2ActionPerformed
//        clientViewModel.pager("Previous");
    }//GEN-LAST:event_btClientPage2ActionPerformed

    private void btClientPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientPage1ActionPerformed
//        clientViewModel.pager("first");
    }//GEN-LAST:event_btClientPage1ActionPerformed

    private void TBReportDeudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBReportDeudaMouseClicked
        if (TBReportDeuda.getSelectedRows().length > 0) {
//            clientViewModel.GetReportClient();
//            clientViewModel.CuotasIntereses();
        }
    }//GEN-LAST:event_TBReportDeudaMouseClicked

    private void TBReportDeudaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBReportDeudaKeyReleased
        if (TBReportDeuda.getSelectedRows().length > 0) {
//            clientViewModel.GetReportClient();
//            clientViewModel.CuotasIntereses();
        }
    }//GEN-LAST:event_TBReportDeudaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBReportDeuda;
    private rsbuttom.RSButtonMetro btClientPage1;
    private rsbuttom.RSButtonMetro btClientPage2;
    private rsbuttom.RSButtonMetro btClientPage3;
    private rsbuttom.RSButtonMetro btClientPage4;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbClientPage;
    private javax.swing.JLabel lbReportName4;
    private javax.swing.JLabel lbReportName5;
    private javax.swing.JLabel lbReportName6;
    private javax.swing.JLabel lbReportName7;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    // End of variables declaration//GEN-END:variables
}
