package views;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;
import libreria.Objeto;
import viewModels.UsuarioViewModel;

/**
 *
 * @author ioriyagamy
 */
public class Usuario extends javax.swing.JPanel {

    private final UsuarioViewModel usuarioViewModel;

    public Usuario() {
        initComponents();

        ArrayList<JLabel> label = new ArrayList<>();
        label.add(lbUsuarioNid);
        label.add(lbUsuarioName);
        label.add(lbUsuarioLastName);
        label.add(lbUsuarioAddrees);
        label.add(lbUsuarioPhone);
        label.add(lbUsuarioEmail);
        label.add(lbUsuario_usuario);
        label.add(lbUsuarioPassword);
        label.add(lbUsuarioImage4);
        label.add(lbUsuarioPage);

        ArrayList<JTextField> txtField = new ArrayList<>();
        txtField.add(txtUsuarioNid);
        txtField.add(txtUsuarioName);
        txtField.add(txtUsuarioLastName);
        txtField.add(txtUsuarioAddrees);
        txtField.add(txtUsuarioPhone);
        txtField.add(txtUsuarioEmail);
        txtField.add(txtUsuario_usuario);
        txtField.add(txtUsuarioPassword);

        Object[] objects = {
            lbUsuarioImage4,
            checkBoxUsuario_State,
            TBUsuarios,
            spinnerUsuarioPage,
            ComboBoxUsuarioRole
        };

        usuarioViewModel = new UsuarioViewModel(objects, txtField, label);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscaUsuario = new javax.swing.JTextField();
        panelClient5 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lbUsuarioImage4 = new javax.swing.JLabel();
        lbUsuarioNid = new javax.swing.JLabel();
        txtUsuarioName = new javax.swing.JTextField();
        lbUsuarioName = new javax.swing.JLabel();
        lbUsuarioLastName = new javax.swing.JLabel();
        txtUsuarioLastName = new javax.swing.JTextField();
        txtUsuarioNid = new javax.swing.JTextField();
        lbUsuarioAddrees = new javax.swing.JLabel();
        txtUsuarioAddrees = new javax.swing.JTextField();
        lbUsuarioPhone = new javax.swing.JLabel();
        txtUsuarioPhone = new javax.swing.JTextField();
        lbUsuarioEmail = new javax.swing.JLabel();
        txtUsuarioEmail = new javax.swing.JTextField();
        btUsuarioAdd = new javax.swing.JButton();
        btUsuarioCancel = new javax.swing.JButton();
        checkBoxUsuario_State = new javax.swing.JCheckBox();
        lbUsuario_usuario = new javax.swing.JLabel();
        txtUsuario_usuario = new javax.swing.JTextField();
        txtUsuarioPassword = new javax.swing.JTextField();
        lbUsuarioPassword = new javax.swing.JLabel();
        ComboBoxUsuarioRole = new javax.swing.JComboBox<>();
        lbUsuarioRole = new javax.swing.JLabel();
        panelClient6 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBUsuarios = TBUsuarios = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jLabel7 = new javax.swing.JLabel();
        spinnerUsuarioPage = new javax.swing.JSpinner();
        btUsuarioPage1 = new rsbuttom.RSButtonMetro();
        btUsuarioPage2 = new rsbuttom.RSButtonMetro();
        btUsuarioPage3 = new rsbuttom.RSButtonMetro();
        btUsuarioPage4 = new rsbuttom.RSButtonMetro();
        lbUsuarioPage = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setPreferredSize(new java.awt.Dimension(785, 30));

        rSButtonMetro1.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cerrar.png"))); // NOI18N
        rSButtonMetro1.setColorHover(new java.awt.Color(51, 51, 51));
        rSButtonMetro1.setColorNormal(new java.awt.Color(102, 102, 102));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1513, Short.MAX_VALUE)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonMetro1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Manjari Thin", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Buscar:");

        txtBuscaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscaUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBuscaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscaUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtBuscaUsuario.setOpaque(false);
        txtBuscaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaUsuarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(293, 293, 293)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addComponent(txtBuscaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelClient5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelClient5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelClient5StateChanged(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbUsuarioImage4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuarioImage4.setIcon(new javax.swing.ImageIcon("/home/ioriyagamy/Documents/software/Hillary/src/Icon/client.png")); // NOI18N
        lbUsuarioImage4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbUsuarioImage4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbUsuarioImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUsuarioImage4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbUsuarioImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioImage4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbUsuarioNid.setText("NID:");

        txtUsuarioName.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuarioName.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuarioName.setOpaque(false);
        txtUsuarioName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioNameKeyTyped(evt);
            }
        });

        lbUsuarioName.setText("NOMBRES:");

        lbUsuarioLastName.setText("APELLIDO:");

        txtUsuarioLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioLastName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuarioLastName.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuarioLastName.setOpaque(false);
        txtUsuarioLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioLastNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioLastNameKeyTyped(evt);
            }
        });

        txtUsuarioNid.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioNid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuarioNid.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioNid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuarioNid.setOpaque(false);
        txtUsuarioNid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioNidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioNidKeyTyped(evt);
            }
        });

        lbUsuarioAddrees.setText("DIRECCION:");

        txtUsuarioAddrees.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioAddrees.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuarioAddrees.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioAddrees.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuarioAddrees.setOpaque(false);
        txtUsuarioAddrees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioAddreesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioAddreesKeyTyped(evt);
            }
        });

        lbUsuarioPhone.setText("TELEFONO:");

        txtUsuarioPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioPhone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuarioPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuarioPhone.setOpaque(false);
        txtUsuarioPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioPhoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioPhoneKeyTyped(evt);
            }
        });

        lbUsuarioEmail.setText("EMAIL:");

        txtUsuarioEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuarioEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuarioEmail.setOpaque(false);
        txtUsuarioEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioEmailKeyTyped(evt);
            }
        });

        btUsuarioAdd.setBackground(new java.awt.Color(255, 255, 255));
        btUsuarioAdd.setText("Agregar");
        btUsuarioAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUsuarioAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioAddActionPerformed(evt);
            }
        });

        btUsuarioCancel.setBackground(new java.awt.Color(255, 255, 255));
        btUsuarioCancel.setText("Cancelar");
        btUsuarioCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUsuarioCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioCancelActionPerformed(evt);
            }
        });

        checkBoxUsuario_State.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxUsuario_State.setText("Estado");
        checkBoxUsuario_State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUsuario_StateActionPerformed(evt);
            }
        });

        lbUsuario_usuario.setText("USUARIO:");

        txtUsuario_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario_usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuario_usuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario_usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuario_usuario.setOpaque(false);
        txtUsuario_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuario_usuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuario_usuarioKeyTyped(evt);
            }
        });

        txtUsuarioPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuarioPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUsuarioPassword.setOpaque(false);
        txtUsuarioPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioPasswordKeyTyped(evt);
            }
        });

        lbUsuarioPassword.setText("PASSWORD:");

        lbUsuarioRole.setText("ROLE");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(btUsuarioAdd))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbUsuario_usuario))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(checkBoxUsuario_State)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btUsuarioCancel)
                            .addComponent(lbUsuarioRole)
                            .addComponent(ComboBoxUsuarioRole, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuario_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                        .addComponent(lbUsuarioNid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioNid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(lbUsuarioPassword)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(lbUsuarioName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(lbUsuarioPhone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioPhone))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(lbUsuarioLastName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(lbUsuarioAddrees)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioAddrees))
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(lbUsuarioEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuarioNid)
                    .addComponent(lbUsuarioName)
                    .addComponent(txtUsuarioName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuarioNid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUsuarioLastName)
                            .addComponent(txtUsuarioLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbUsuarioPhone)
                            .addComponent(txtUsuarioPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUsuarioAddrees)
                            .addComponent(txtUsuarioAddrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUsuarioEmail)
                            .addComponent(txtUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUsuario_usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsuarioPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuarioPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lbUsuarioRole)
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxUsuario_State, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboBoxUsuarioRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUsuarioAdd)
                    .addComponent(btUsuarioCancel))
                .addContainerGap())
        );

        panelClient5.addTab("Regitro de Usuarios", jPanel12);

        panelClient6.setBackground(new java.awt.Color(255, 255, 255));
        panelClient6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelClient6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelClient6StateChanged(evt);
            }
        });

        TBUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        TBUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TBUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TBUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBUsuariosMouseClicked(evt);
            }
        });
        TBUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TBUsuariosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TBUsuarios);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelClient6.addTab("Lista de Usuarios", jPanel14);

        jLabel7.setText("Registro Por Paginas");

        spinnerUsuarioPage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerUsuarioPageStateChanged(evt);
            }
        });

        btUsuarioPage1.setBackground(new java.awt.Color(255, 255, 255));
        btUsuarioPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/left-arrow(1).png"))); // NOI18N
        btUsuarioPage1.setColorBorde(null);
        btUsuarioPage1.setColorHover(new java.awt.Color(102, 102, 102));
        btUsuarioPage1.setColorNormal(new java.awt.Color(255, 255, 255));
        btUsuarioPage1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUsuarioPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioPage1ActionPerformed(evt);
            }
        });

        btUsuarioPage2.setBackground(new java.awt.Color(255, 255, 255));
        btUsuarioPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/left-arrow.png"))); // NOI18N
        btUsuarioPage2.setColorBorde(null);
        btUsuarioPage2.setColorHover(new java.awt.Color(102, 102, 102));
        btUsuarioPage2.setColorNormal(new java.awt.Color(255, 255, 255));
        btUsuarioPage2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUsuarioPage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioPage2ActionPerformed(evt);
            }
        });

        btUsuarioPage3.setBackground(new java.awt.Color(255, 255, 255));
        btUsuarioPage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next.png"))); // NOI18N
        btUsuarioPage3.setColorBorde(null);
        btUsuarioPage3.setColorHover(new java.awt.Color(102, 102, 102));
        btUsuarioPage3.setColorNormal(new java.awt.Color(255, 255, 255));
        btUsuarioPage3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUsuarioPage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioPage3ActionPerformed(evt);
            }
        });

        btUsuarioPage4.setBackground(new java.awt.Color(255, 255, 255));
        btUsuarioPage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/right-arrow.png"))); // NOI18N
        btUsuarioPage4.setColorBorde(null);
        btUsuarioPage4.setColorHover(new java.awt.Color(102, 102, 102));
        btUsuarioPage4.setColorNormal(new java.awt.Color(255, 255, 255));
        btUsuarioPage4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUsuarioPage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioPage4ActionPerformed(evt);
            }
        });

        lbUsuarioPage.setText("Paginas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelClient5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelClient6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerUsuarioPage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btUsuarioPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btUsuarioPage2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btUsuarioPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btUsuarioPage4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lbUsuarioPage)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelClient5, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panelClient6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbUsuarioPage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerUsuarioPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btUsuarioPage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btUsuarioPage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btUsuarioPage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btUsuarioPage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        this.hide();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void lbUsuarioImage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUsuarioImage4MouseClicked
        Objeto.uploadImage.loadImage(lbUsuarioImage4);
    }//GEN-LAST:event_lbUsuarioImage4MouseClicked

    private void txtUsuarioNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioNameKeyReleased
        if (txtUsuarioName.getText().equals("")) {
            lbUsuarioName.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuarioName.setText("NOMBRE");
            lbUsuarioName.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuarioNameKeyReleased

    private void txtUsuarioNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioNameKeyTyped
        Objeto.events.textKeyPress(evt);
    }//GEN-LAST:event_txtUsuarioNameKeyTyped

    private void txtUsuarioLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioLastNameKeyReleased
        if (txtUsuarioLastName.getText().equals("")) {
            lbUsuarioLastName.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuarioLastName.setText("APELLIDO");
            lbUsuarioLastName.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuarioLastNameKeyReleased

    private void txtUsuarioLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioLastNameKeyTyped
        Objeto.events.textKeyPress(evt);
    }//GEN-LAST:event_txtUsuarioLastNameKeyTyped

    private void txtUsuarioNidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioNidKeyReleased
        if (txtUsuarioNid.getText().equals("")) {
            lbUsuarioNid.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuarioNid.setText("NID");
            lbUsuarioNid.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuarioNidKeyReleased

    private void txtUsuarioNidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioNidKeyTyped
        Objeto.events.numbreKeyPress(evt);
    }//GEN-LAST:event_txtUsuarioNidKeyTyped

    private void txtUsuarioAddreesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioAddreesKeyReleased
        if (txtUsuarioAddrees.getText().equals("")) {
            lbUsuarioAddrees.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuarioAddrees.setText("DIRECCION");
            lbUsuarioAddrees.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuarioAddreesKeyReleased

    private void txtUsuarioAddreesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioAddreesKeyTyped
        Objeto.events.textKeyPress(evt);
    }//GEN-LAST:event_txtUsuarioAddreesKeyTyped

    private void txtUsuarioPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioPhoneKeyReleased
        if (txtUsuarioPhone.getText().equals("")) {
            lbUsuarioPhone.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuarioPhone.setText("TELEFONO");
            lbUsuarioPhone.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuarioPhoneKeyReleased

    private void txtUsuarioPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioPhoneKeyTyped
        Objeto.events.numbreKeyPress(evt);
    }//GEN-LAST:event_txtUsuarioPhoneKeyTyped

    private void txtUsuarioEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioEmailKeyReleased
        if (txtUsuarioEmail.getText().equals("")) {
            lbUsuarioEmail.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuarioEmail.setText("EMAIL");
            lbUsuarioEmail.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuarioEmailKeyReleased

    private void txtUsuarioEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEmailKeyTyped

    private void btUsuarioAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioAddActionPerformed

        usuarioViewModel.RegistrarUsuario();
    }//GEN-LAST:event_btUsuarioAddActionPerformed

    private void btUsuarioCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioCancelActionPerformed
        usuarioViewModel.Restablecer();
    }//GEN-LAST:event_btUsuarioCancelActionPerformed

    private void checkBoxUsuario_StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxUsuario_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxUsuario_StateActionPerformed

    private void panelClient5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelClient5StateChanged

    }//GEN-LAST:event_panelClient5StateChanged

    private void txtUsuario_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuario_usuarioKeyReleased
        if (txtUsuario_usuario.getText().equals("")) {
            lbUsuario_usuario.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuario_usuario.setText("USUARIO");
            lbUsuario_usuario.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuario_usuarioKeyReleased

    private void txtUsuario_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuario_usuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario_usuarioKeyTyped

    private void txtUsuarioPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioPasswordKeyReleased
        if (txtUsuarioPassword.getText().equals("")) {
            lbUsuarioPassword.setForeground(new Color(102, 102, 102));
        } else {
            lbUsuarioPassword.setText("PASSWORD");
            lbUsuarioPassword.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_txtUsuarioPasswordKeyReleased

    private void txtUsuarioPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioPasswordKeyTyped

    private void panelClient6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelClient6StateChanged

    }//GEN-LAST:event_panelClient6StateChanged

    private void TBUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBUsuariosKeyReleased
        if (TBUsuarios.getSelectedRows().length > 0) {
            usuarioViewModel.GetUsuario();
        }
    }//GEN-LAST:event_TBUsuariosKeyReleased

    private void TBUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBUsuariosMouseClicked
        if (TBUsuarios.getSelectedRows().length > 0) {
            usuarioViewModel.GetUsuario();
        }
    }//GEN-LAST:event_TBUsuariosMouseClicked

    private void spinnerUsuarioPageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerUsuarioPageStateChanged
        usuarioViewModel.Registro_Paginas();
    }//GEN-LAST:event_spinnerUsuarioPageStateChanged

    private void btUsuarioPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioPage1ActionPerformed
        usuarioViewModel.Paginador("first");
    }//GEN-LAST:event_btUsuarioPage1ActionPerformed

    private void btUsuarioPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioPage2ActionPerformed
        usuarioViewModel.Paginador("Previous");
    }//GEN-LAST:event_btUsuarioPage2ActionPerformed

    private void btUsuarioPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioPage3ActionPerformed
        usuarioViewModel.Paginador("Next");
    }//GEN-LAST:event_btUsuarioPage3ActionPerformed

    private void btUsuarioPage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioPage4ActionPerformed
        usuarioViewModel.Paginador("Last");
    }//GEN-LAST:event_btUsuarioPage4ActionPerformed

    private void txtBuscaUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaUsuarioKeyReleased
        usuarioViewModel.Paginador("first");
        usuarioViewModel.SearchUsuarios(txtBuscaUsuario.getText());
    }//GEN-LAST:event_txtBuscaUsuarioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxUsuarioRole;
    private javax.swing.JTable TBUsuarios;
    private javax.swing.JButton btUsuarioAdd;
    private javax.swing.JButton btUsuarioCancel;
    private rsbuttom.RSButtonMetro btUsuarioPage1;
    private rsbuttom.RSButtonMetro btUsuarioPage2;
    private rsbuttom.RSButtonMetro btUsuarioPage3;
    private rsbuttom.RSButtonMetro btUsuarioPage4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxUsuario_State;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbUsuarioAddrees;
    private javax.swing.JLabel lbUsuarioEmail;
    private javax.swing.JLabel lbUsuarioImage4;
    private javax.swing.JLabel lbUsuarioLastName;
    private javax.swing.JLabel lbUsuarioName;
    private javax.swing.JLabel lbUsuarioNid;
    private javax.swing.JLabel lbUsuarioPage;
    private javax.swing.JLabel lbUsuarioPassword;
    private javax.swing.JLabel lbUsuarioPhone;
    private javax.swing.JLabel lbUsuarioRole;
    private javax.swing.JLabel lbUsuario_usuario;
    private javax.swing.JTabbedPane panelClient5;
    private javax.swing.JTabbedPane panelClient6;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private javax.swing.JSpinner spinnerUsuarioPage;
    private javax.swing.JTextField txtBuscaUsuario;
    private javax.swing.JTextField txtUsuarioAddrees;
    private javax.swing.JTextField txtUsuarioEmail;
    private javax.swing.JTextField txtUsuarioLastName;
    private javax.swing.JTextField txtUsuarioName;
    private javax.swing.JTextField txtUsuarioNid;
    private javax.swing.JTextField txtUsuarioPassword;
    private javax.swing.JTextField txtUsuarioPhone;
    private javax.swing.JTextField txtUsuario_usuario;
    // End of variables declaration//GEN-END:variables
}
